# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1clxtengG98ATD_izGMVpnCcjX_03g-4q

STRİNG
"""

#https://www.youtube.com/watch?v=HGOBQPFzWKo&ab_channel=freeCodeCamp.org
mylist=['banana','apple','cherry']

print(mylist)

mylist2=()
print(mylist2)

mylist3=[3,True,'APPLE','APPLE']
print(mylist3)

element=mylist[0]
print(element)

element=mylist[-3]
print(element)

for i in mylist:
  print(i)

if "banana" in mylist:
   print("yes")
else:
  print("no")

if "lemon" in mylist:
   print("yes")
else:
  print("no")

len(mylist)

mylist=['banana','apple','cherry']

mylist.append("lemon")
print(mylist)

mylist.insert(1,"blueberry")
print(mylist)

item=mylist.pop()
print(item)
print(mylist)

mylist=['banana','apple','cherry']

mylist.remove("banana")
print(mylist)

mylist.remove("cherly1")
print(mylist)

mylist.clear()
print(mylist)

mylist.reverse()
print(mylist)

mylist.sort()
print(mylist)

mylist=[6,4,-4,10,3,2,3,-6,4]

mylist.sort()
print(mylist)

mylist=[6,4,-4,10,3,2,3,-6,4]

mylist1=sorted(mylist)
print(mylist)
print(mylist1)

mylist1=[0]*5
print(mylist1)

mylist2=[1,2,3,4,5]
print(mylist2)

new_list=mylist1+mylist2
print(new_list)

mylist1=[1,2,3,4,5,6,7,8,9]
a=mylist1[1:5]

print(a)

a=mylist1[:5]
print(a)

a=mylist1[1:]
print(a)

a=mylist1[::1]
print(a)

a=mylist1[::2]
print(a)

a=mylist1[::-1]
print(a)

list_org=["banana","cherry","apple"]
print(list_org)

list_copy=list_org

list_copy.append("lemon")

print(list_copy)
print(list_org)

list_org=["banana","cherry","apple"]
print(list_org)

list_copy=list_org.copy()

list_copy.append("lemon")

print(list_copy)
print(list_org)

list_org=["banana","cherry","apple"]
list_copy=list(list_org)

list_copy.append("lemon")

print(list_copy)
print(list_org)

mylist=[1,2,3,4,5,6]

b=[i*i for i in mylist]
print(b)

mylist=[1,2,3,4,5,6,7,8,9,10]
new_list=list(filter(lambda x:x%2==0,mylist))
print(mylist)
print(new_list)

even_squares = [x*x  for x in mylist if x % 2 == 0]
print(even_squares)

